sites/urls.py
from django.urls import path
from sites.views import *
from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = 'sites'

urlpatterns =[
    path('', index, name='index'),
    #path('login/', login, name='login'),
    path('base/', base, name='base'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', logout_exit, name='logout'),
    path('open_1c/', open_1c, name='open_1c'),
    path('close_1c/', close_1c, name='close_1c'),
    path('open_mik/', open_mik, name='open_mik'),
    path('close_mik/', close_mik, name='close_mik'),
    path('mik_res/', mik_res, name='mik_res'),
    path('rules/', rules, name='rules'),
    path('info/', info, name='info'),
    path('menu/', menu, name='menu'),
    path('menus/', menus, name='menus'),
    path('addlink/', addlink, name='addlink'),
    path('phones/', phones, name='phones'),
    path('add_phone/', add_phone, name='add_phone'),
    path('def_test/', def_test, name='def_test'),
    path('profile/', profile, name='profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitez/urls.py
from django.contrib import admin
from django.urls import path, include
from sites.views import index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sites/', include('sites.urls', namespace = 'sites')),
    path('',index, name = 'index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sites/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

# Create your models here.


class add_links(models.Model):
    title = models.CharField('Название', max_length=30)
    link = models.CharField('Ссылка', max_length=250)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Ссылка'
        verbose_name_plural = 'Ссылки'

class menu_bd(models.Model):
    title = models.CharField('Название', max_length=30)
    link = models.CharField('Ссылка', max_length=250)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пункт меню'
        verbose_name_plural = 'Пункты меню'

class phone(models.Model):
    title = models.CharField('ФИО', max_length=30)
    phone = models.CharField('Телефон', max_length=250)
    job = models.CharField('Должность', max_length=250)
    mail = models.CharField('Почта', max_length=250)
    photo = models.ImageField(upload_to='images/',blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Добавить телефон'
        verbose_name_plural = 'Сотрудники'

    # def search(self, seach):
    #     qs = self.get_queryset()
    #     if seach:
    #         qs = qs.filter(Q(name__icontains=seach) | Q(description__icontains=seach))
    #     return qs

#Расширение стандарной модели админки
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    first_name1 = models.CharField(max_length=30, blank=True)
    last_name1 = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.user.username

# class MyUser(AbstractUser):
#      phone_number1 = models.CharField(max_length=20, blank=True)

sites/forms.py
from django import forms
from django.forms import ModelForm, TextInput, Textarea
from .models import *

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)

class addlinkForm(ModelForm):
    class Meta:
        model = add_links
        fields = ['title','link']
        widgets = {
            "title": TextInput(attrs={
                'class':'form-control',
                'placeholder':'Название ссылки'
            }),
            "link": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ссылка'
            })
        }

class addPhone(ModelForm):
    class Meta:
        model = phone
        fields = ['title','phone','job','mail']
        widgets = {
            "title": TextInput(attrs={
                'class':'form-control',
                'placeholder':'ФИО'
            }),
            "phone": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Телефон'
            }),
            "job": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Должность'
            }),
            "mail": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Почта'
            }),
        }


class SearchForm(forms.Form):
    search_query = forms.CharField(label='Search', max_length=100)

class PhotoImg(forms.ModelForm):
    class Meta:
        model = phone
        fields = ['photo']

#Расширение стандарной модели админки
class ProfileForm(forms.ModelForm):
    first_name1 = forms.CharField(widget=forms.TextInput(attrs={'class' : 'menuextras'}))

    class Meta:
        model = Profile
        fields = ['avatar', 'first_name1', 'last_name1']

sites/views.py
from aiogram.utils.mixins import DataMixin
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.apps import apps
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import redirect
from .forms import *
from  .models import *
from django.db.models import Q
from django.contrib.auth.decorators import login_required


import paramiko

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
passwd = "Jac" #Пароль для скриптов!!!


#from .forms import LoginForm

# Create your views here.
from django.urls import reverse_lazy
from sites.forms import LoginForm


def index(request):
    links = add_links.objects.all()
    return render(request, 'sites/index.html', {"links": links})

def phones(request):
    links_phone = phone.objects.all()
    result =''
    # Форма поиска
    form = SearchForm(request.GET or None)
    search = []
    if form.is_valid():
        search_query = form.cleaned_data['search_query']
        search = phone.objects.filter(Q(title__icontains=search_query)|Q(phone__icontains=search_query)|Q(job__icontains=search_query)|Q(mail__icontains=search_query))
    #Сохранение фото
    form1 = PhotoImg(request.POST, request.FILES)
    if request.method == 'POST':
        if form1.is_valid():
            form1.save()
            return redirect('product_list')
        else:
            form1 = ProductForm()
    return render(request, 'sites/phone.html', {"links_phone": links_phone, 'form':form,'form1':form1, 'search':search})

# def menu(request):
#     links_menu = menu_bd.objects.all()
#     return render(request, 'sites/menu.html',{"links_menu": links_menu})

def menu(request):
    links = add_links.objects.all()
    return render(request, 'sites/menu.html',{"links": links})

def add_phone(request):
    error = ''
    if request.method == 'POST':
        form = addPhone(request.POST)
        if form.is_valid():
            form.save()
        else:
            error = 'Форма не верная'
    form = addPhone()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'sites/add_phone.html', data)

def addlink(request):
    error = ''
    if request.method =='POST':
        form = addlinkForm(request.POST)
        if form.is_valid():
            form.save()
            print(form.cleaned_data)
        else:
            error = 'Форма не верная'
    form = addlinkForm()
    data = {
        'form':form,
        'error': error,
    }
    return render(request, 'sites/addlink.html', data)




#def login(request):
 #   return render(request, 'sites/login.html')

def base(request):
    links_menu = menu_bd.objects.all()
    return render(request, 'sites/base.html',{"links_menu": links_menu})

def menus(request):
    return render(request, 'sites/menus.html')

def def_test(request):
    sum = ''
    if request.method == 'POST':
        my_field_value = int(request.POST.get('my_field'))
        sum = 4 + my_field_value
        print(sum)
        if  my_field_value == 5:
            return redirect('index')
    else:
        my_field_value = None
    return render(request, 'sites/def_test.html', {'my_field': my_field_value, 'sum' : sum })

def rules(request):
    return render(request, 'sites/rules.html')

def info(request):
    return render(request, 'sites/info.html')

# def phone(request):
#     return render(request, 'sites/phone.html')


def open_1c (request): #Открыть правило для 1С SQL снаружи
    try:
        client.connect(hostname='10.100.2.1', port=6666, username="bka", password=passwd, look_for_keys=False,
                       allow_agent=False)
        _stdin, _stdout, _stderr = client.exec_command('ip firewall nat enable numbers=5')
        return render(request, 'sites/return.html')
        #return HttpResponse("Выполнено")
    except Exception:
        return render(request, 'sites/error.html')

def close_1c (request): #Закрыть правило для 1С SQL снаружи
    try:
        client.connect(hostname='10.100.2.1', port=6666, username="bka", password=passwd, look_for_keys=False,
                       allow_agent=False)
        _stdin, _stdout, _stderr = client.exec_command('ip firewall nat disable numbers=5')
        return render(request, 'sites/return.html')
        #return HttpResponse("Выполнено")
    except Exception:
        return render(request, 'sites/error.html')

def open_mik (request): #Закрыть правило для mikrotik снаружи
    try:
        client.connect(hostname='10.100.2.1', port=6666, username="bka", password=passwd, look_for_keys=False,
                       allow_agent=False)
        _stdin, _stdout, _stderr = client.exec_command('ip firewall nat enable numbers=2')
        return render(request, 'sites/return.html')
        #return HttpResponse("Выполнено")
    except Exception:
        return render(request, 'sites/error.html')


def close_mik (request): #Закрыть правило для mikrotik снаружи
    try:
        client.connect(hostname='10.100.2.1', port=6666, username="bka", password=passwd, look_for_keys=False,
                       allow_agent=False)
        _stdin, _stdout, _stderr = client.exec_command('ip firewall nat disable numbers=2')
        return render(request, 'sites/return.html')
        #return HttpResponse("Выполнено")
    except Exception:
        return render(request, 'sites/error.html')

def mik_res (request): #Перезагрузка MIkrotik
    try:
        client.connect(hostname='10.100.2.1', port=6666, username="bka", password=passwd, look_for_keys=False,
                       allow_agent=False)
        _stdin, _stdout, _stderr = client.exec_command('system reboot')
        return render(request, 'sites/return.html')
        #return HttpResponse("Выполнено")
    except Exception:
        return render(request, 'sites/error.html')

# def login_view(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user = authenticate(request, username=username, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect('home')
#     else:
#         form = LoginForm()
#     return render(request, 'sites/login.html', {'sites:form': form})

# class LoginUser(DataMixin, LoginView):
#     form_class = AuthenticationForm
#     template_name = 'sites/login.html'

    #
    # def get_context_data(self, *, object_list=None, **kwargs):
    #      context = super().get_context_data(**kwargs)
    #      c_def = self.get_user_context(title="Авторизация")
    #      return dict(list(context.items()) + list(c_def.items()))
class CustomLoginView(LoginView):
    authentication_form = AuthenticationForm
    template_name = 'sites/login.html'

    def get_success_url(self):
        return reverse_lazy('sites:index')

def logout_exit(request):
    logout(request)
    return redirect('index')

@login_required
def profile(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)

        if form.is_valid():
            form.save()
    else:
        form = ProfileForm(instance=profile)

    return render(request,'sites/profile.html', {'user': user, 'profile': profile,'form': form},)

sites/templates/sites/add_phone.html
{% extends 'sites/base.html' %}

{% block menu %}
{% endblock %}



{% block content %}

<style>
	.center_menu{
	text-align : left;
	}
</style>

        <div class="section">
	    	<div class="container">
				<div class="row">
					<div class="col-md-11">
						<div class="service-wrapper">
							{% if request.user.is_authenticated %}
								<form method="post">
									{% csrf_token %}
									{{ form.title }}<br>
									{{ form.phone }}<br>
									{{ form.job }}<br>
									{{ form.mail }}<br>
									{{ form.photo }}<br>
									<button type="submit">Отправить</button>
									<span>{{ error }}</span>
								</form>

							{% else %}
								<h3>Необходимо зерегистрироваться</h3>
							{% endif %}
						</div>
					</div>

				</div>
			</div>
		</div>

{% endblock %}

sites/templates/sites/addlink.html
{% extends 'sites/base.html' %}

{% block menu %}
{% endblock %}



{% block content %}

<style>
	.center_menu{
	text-align : left;
	}
</style>

        <div class="section">
	    	<div class="container">
				<div class="row">
					<div class="col-md-11">
						<div class="service-wrapper">
							{% if request.user.is_authenticated %}
								<form method="post">
									{% csrf_token %}
									{{ form.title }}<br>
									{{ form.link }}
									<button type="submit">Отправить</button>
									<span>{{ error }}</span>
								</form>

							{% else %}
								<h3>Необходимо зерегистрироваться</h3>
							{% endif %}
						</div>
					</div>

				</div>
			</div>
		</div>

{% endblock %}

sites/templates/sites/base.html
{% load static %}
{% load get_group %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>mPurpose - Multipurpose Feature Rich Bootstrap Template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/icomoon-social.css' %}">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="{% static 'css/leaflet.css' %}" />
		<!--[if lte IE 8]>
		    <link rel="stylesheet" href="{% static 'css/leaflet.ie.css' %}" />
		<![endif]-->
		<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="{% static 'js/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
    </head>
    <body>

        <!-- Navigation & Logo-->
        <div class="mainmenu-wrapper">
	        <div >
	        	<div class="menuextras">
					<div class="extras">

						<ul>
							<li><img src="{{ user.profile.avatar.url }}" alt="{{ user.username }}" style="max-height: 50px; max-width: 50px;"></li>
							{{ user.profile.birth_date }}
		        		<li>{% if request.user.is_authenticated %}


							<h4>Вы вошли как <b>{{ user.username }}</b></h4>
							<h4><b>Привет {{ user.first_name }}</b></h4>
							<h4><b>{{ user.date_joined }}</b></h4>
							{% else %}
							<a href="{% url 'sites:login' %}"><h4><b>Войти</b></h4></a></li>
							{% endif %}
							{% if request.user.is_authenticated %}
							<li><a href="{% url 'sites:logout' %}"><h4><b>Выйти</b></h4></a></li>
							{% endif %}
			        	</ul>
					</div>
		        </div>
				<!-- <nav id="mainmenu" class="mainmenu">-->
		        <nav id="mainmenu" class="mainmenu">
					<ul>
						<li class="logo-wrapper"><a href="{% url 'index' %}"><img src="{% static 'img/mPurpose-logo.png' %}" alt="Multipurpose Twitter Bootstrap Template"></a></li>
								{% block menu %}
								{% endblock %}
						{% if request.user.is_authenticated %}
							<li class="active">
								<a href="{% url 'index' %}">Главная</a>
							</li>
							<li class="active">
								<a href="{% url 'sites:info' %}">Info</a>
							</li>
						<li class="active">
								<a href="{% url 'sites:phones' %}">Справочник</a>
							</li>
						{% if request.user|has_group:"admin" %}

							<li class="active">
								<a href="{% url 'sites:menu' %}">Ссылки</a>
							</li>
													<li class="active">
								<a href="{% url 'sites:rules' %}">Все правила</a>
							</li>
						    <li class="active">
								<a href="{% url 'sites:add_phone' %}">Добавить телефон</a>
							</li>
													<li class="active">
								<a href="{% url 'sites:addlink' %}">Добавить ссылку</a>
							</li>
							</li>
							<li class="active">
								<a href="{% url 'sites:profile' %}">Профиль</a>
							</li>
						    <li class="active">
								<a href="{% url 'sites:def_test' %}">Тест данные</a>
							</li>
						{% endif %}

						{% endif %}

						</li>
						<!-- <li>
							<a href="credits.html">Credits</a>
						</li> -->
					</ul>

			</div>
		</div>

        <!-- Homepage Slider -->

				<div class="sequence-pagination-wrapper">
					<ul class="sequence-pagination">
						<li>1</li>
						<li>2</li>
						<li>3</li>
					</ul>
				</div>
			</div>
        </div>
        <!-- End Homepage Slider -->

		<!-- Press Coverage -->

		<!-- Press Coverage -->

		<!-- Services -->
        <div class="section">
	        <div class="container">
	        	<div class="row">

	        	</div>
	        </div>
	    </div>
	    <!-- End Services -->



		{% block content %}
		{% endblock %}

    </body>
</html>

sites/templates/sites/def_test.html
{% extends 'sites/base.html' %}
{% block content %}
								<form method="post"><br><br>
  								{% csrf_token %}
  								<input type="text" name="my_field" id="my_field_id" value="Введите данные">
  									<button type="submit">Submit</button>
								</form>
								{{ sum }}
{% endblock %}

sites/templates/sites/error.html
{% extends 'sites/base.html' %}

{% block content %}


	 	<div class="container">
			<div class="row">

					<div class="service-wrapper">
								<h3>Ошибка выполнения</h3>

					</div>

			</div>
	 	</div>

{% endblock %}

sites/templates/sites/index.html
{% extends 'sites/base.html' %}

{% block menu %}
	<li class="active">
		<a href="{% url 'index' %}">Главная</a>
	</li>
	<li class="active">
		<a href="{% url 'sites:info' %}">Info</a>
	</li>
{% endblock %}

{% block content %}
<style>
	.center_menu{
	text-align : left;
	}
</style>

        <div class="section">
	    	<div class="container">
				<div class="row">
					<div class="col-md-4 col-sm-6">
						<div class="service-wrapper">
							{% if request.user.is_authenticated %}
								<h3>Меню</h3>
								<a href="{% url 'sites:rules' %}" class="btn">Правила Mikrotik</a><br> <br>
							{% else %}
								<h3>Необходимо зерегистрироваться</h3>
							{% endif %}
						</div>
					</div>

				</div>
			</div>
		</div>

{% endblock %}

sites/templates/sites/info.html
{% extends 'sites/base.html' %}

{% block menu %}

{% endblock %}

{% block content %}
<style>
	.center_txt{
	text-align : left;
	text-indent : 150px ;
	}
</style>
<div class = "center_txt"><h4><b>Вход на удаленный стол (RDP Терминал): dd.okna-zeon.ru:49988 или 92.241.17.41:49988</b></h4><br><br></div>

<div class = "center_txt"><h4><b>Вход на удаленный стол (RDP 1С): dd.okna-zeon.ru:49986 или 92.241.17.41:49986</b></h4><br><br></div>

<div class = "center_txt"><h4><b>Вход на удаленный стол (RDP HOST): dd.okna-zeon.ru:49901 или 92.241.17.41:49901</b></h4><br><br></div>

<div class = "center_txt"><h4><b>Вход на удаленный стол (RDP BCP PC): dd.okna-zeon.ru:49900 или 92.241.17.41:49900</b></h4><br><br></div>


{% endblock %}

sites/templates/sites/login.html
{% extends 'sites/base.html' %}
{% load static %}

{% block content %}




<div class = "center_menu1">
    <h2>Login</h2>
    <form method="post">

        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>
</div>


{% endblock %}

sites/templates/sites/menu.html
{% extends 'sites/base.html' %}

{% block menu %}

{% endblock %}

{% block content %}
<style>
	.center_txt{
	text-align : left;
	text-indent : 150px ;
	}
</style>
<div class="section">
	    	<div class="container">
				<div class="row">
					<div class="col-md-11">
						<div class="service-wrapper">
						{% for link in links %}
							<div class="center_txt">
							<h3><li class="active">
								<a href="{{ link.link }}">{{ link.title }} </a>
							</li></h3>
							</div>
						{% endfor %}

						</div>
					</div>
				</div>
			</div>
		</div>


{% endblock %}

sites/templates/sites/phone.html
{% extends 'sites/base.html' %}

{% block menu %}
{% endblock %}

{% block content %}

<div class="section">
	    	<div class="container">
				<div class="row">
					<div class="col-md-11">
						<div class="service-wrapper">

								<table border="1" bordercolor="grey" width="800" align="center">
								<tr><th align="center">ФИО</th>
									<th align="center">Телефон</th>
									<th align="center">Должность</th>
									<th align="center">Почта</th>
								</tr> <!--ряд с ячейками заголовков-->
									{% for link in links_phone %}
										<tr><td>{{ link.title }}</td>
											<td>{{ link.phone }}</td>
											<td>{{ link.job }}</td>
											<td>{{ link.mail }}</td>
											<td>
											{% if link.photo %}
    											<img src="{{ link.photo.url }}" alt="Product Image">
											{% endif %}
											</td>
										</tr> <!--ряд с ячейками тела таблицы-->
									{% endfor %}
									<!--Поиск-->
								</table>


							<form  method="GET">
								{% csrf_token %}
							<h1>Поиск</h1>
							<form method="get">
								{{ form.as_p }}	<button type="submit">Поиск</button>
							</form>
							{% if search %}
								<ul>
									{% for searc in search %}
										<b>{{ searc.title }} {{ searc.phone }}  {{ searc.job }}  {{ searc.mail }}
											<img src="{{ searc.photo.url }}" alt="Изображение">
										<br> <br></b>
									{% endfor %}
								</ul>
							{% endif %}

							</form>

								{% for results in result %}
  									<h2>{{ result.title }}</h2>
  									<p>{{ result.phone }}</p>
								{% endfor %}

						</div>
					</div>
				</div>
			</div>
		</div>
{% endblock %}

sites/templates/sites/profile.html
{% extends 'sites/base.html' %}

{% block menu %}

{% endblock %}

{% block content %}


<p>Добро пожаловать, {{ user.username }}!</p>

<form method="post" action="{% url 'sites:profile' %}">
    {{ profile.first_name1 }}
    {% csrf_token %}
    {{ form.as_p }}
    {{ form.first_name1 }}
    <button type="submit">Сохранить</button>
</form>


{% endblock %}

sites/templates/sites/return.html
{% extends 'sites/base.html' %}

{% block content %}


	 	<div class="container">
			<div class="row">

					<div class="service-wrapper">
								<h3>Выполнено успешно</h3>
								{% if request.user.is_authenticated %}
									<a href="{% url 'sites:index' %}" class="btn">На главную</a><br> <br>
								{% endif %}
					</div>

			</div>
	 	</div>

{% endblock %}

sites/templates/sites/rules.html
{% extends 'sites/base.html' %}
{% load get_group %}

{% block menu %}

{% endblock %}

{% block content %}
        <div class="section">
	    	<div class="container">
				<div class="row">
					<div class="col-md-4 col-sm-6">
						<div class="service-wrapper">
							<h3>Правила для 1с</h3>
							{% if request.user.is_authenticated %}
							<a href="{% url 'sites:open_1c' %}" class="btn">Открыть</a><br> <br>
							<a href="{% url 'sites:close_1c' %}" class="btn">Закрыть </a><br> <br>
							{% endif %}
						</div>
					</div>
					<div class="col-md-4 col-sm-6">
						<div class="service-wrapper">
								{% if request.user|has_group:"admin" %}
									 <!--<!Видно только ADMIN-->
									<h3>Правила Микротика</h3>
									<a href="{% url 'sites:open_mik' %}" class="btn">Открыть снаружи</a><br> <br>
									<a href="{% url 'sites:close_mik' %}" class="btn">Закрыть снаружи</a><br> <br>
									<a href="{% url 'sites:mik_res' %}" class="btn">Перезагрузка Mikrotik</a><br> <br>
								{% endif %}

						</div>
					</div>
					<div class="col-md-4 col-sm-6">
						<div class="service-wrapper">
							{% if request.user|has_group:"admin" %}
								 <!--<!Видно только ADMIN-->
									<h3>Остальное</h3>
									<a href="#" class="btn">Открыть к ПК бекап</a><br> <br>
									<a href="#" class="btn">Закрыть ПК бекап</a><br> <br>
									<a href="#" class="btn">Открыть основной хост</a><br> <br>
									<a href="#" class="btn">Закрыть основной хост</a>
							{% endif %}
						</div>
					</div>
					</div>
				</div>
			</div>
		</div>
{% endblock %}