sites/urls.py
from django.urls import path
from sites.views import *
from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = 'sites'

urlpatterns =[
    path('', index, name='index'),
    #path('login/', login, name='login'),
    path('base/', base, name='base'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', logout_exit, name='logout'),
    path('open_1c/', open_1c, name='open_1c'),
    path('close_1c/', close_1c, name='close_1c'),
    path('open_mik/', open_mik, name='open_mik'),
    path('close_mik/', close_mik, name='close_mik'),
    path('mik_res/', mik_res, name='mik_res'),
    path('rules/', rules, name='rules'),
    path('info/', info, name='info'),
    path('menu/', menu, name='menu'),
    path('menus/', menus, name='menus'),
    path('addlink/', addlink, name='addlink'),
    path('phones/', phones, name='phones'),
    path('add_phone/', add_phone, name='add_phone'),
    path('def_test/', def_test, name='def_test'),
    path('profile/', profile, name='profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitez/urls.py
from django.contrib import admin
from django.urls import path, include
from sites.views import index
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sites/', include('sites.urls', namespace = 'sites')),
    path('',index, name = 'index'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sites/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

# Create your models here.


class add_links(models.Model):
    title = models.CharField('Название', max_length=30)
    link = models.CharField('Ссылка', max_length=250)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Ссылка'
        verbose_name_plural = 'Ссылки'

class menu_bd(models.Model):
    title = models.CharField('Название', max_length=30)
    link = models.CharField('Ссылка', max_length=250)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Пункт меню'
        verbose_name_plural = 'Пункты меню'

class phone(models.Model):
    title = models.CharField('ФИО', max_length=30)
    phone = models.CharField('Телефон', max_length=250)
    job = models.CharField('Должность', max_length=250)
    mail = models.CharField('Почта', max_length=250)
    photo = models.ImageField(upload_to='images/',blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Добавить телефон'
        verbose_name_plural = 'Сотрудники'

    # def search(self, seach):
    #     qs = self.get_queryset()
    #     if seach:
    #         qs = qs.filter(Q(name__icontains=seach) | Q(description__icontains=seach))
    #     return qs

#Расширение стандарной модели админки
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    first_name1 = models.CharField(max_length=30, blank=True)
    last_name1 = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.user.username

# class MyUser(AbstractUser):
#      phone_number1 = models.CharField(max_length=20, blank=True)

sites/forms.py
from django import forms
from django.forms import ModelForm, TextInput, Textarea
from .models import *

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)

class addlinkForm(ModelForm):
    class Meta:
        model = add_links
        fields = ['title','link']
        widgets = {
            "title": TextInput(attrs={
                'class':'form-control',
                'placeholder':'Название ссылки'
            }),
            "link": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Ссылка'
            })
        }

class addPhone(ModelForm):
    class Meta:
        model = phone
        fields = ['title','phone','job','mail']
        widgets = {
            "title": TextInput(attrs={
                'class':'form-control',
                'placeholder':'ФИО'
            }),
            "phone": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Телефон'
            }),
            "job": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Должность'
            }),
            "mail": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Почта'
            }),
        }


class SearchForm(forms.Form):
    search_query = forms.CharField(label='Search', max_length=100)

class PhotoImg(forms.ModelForm):
    class Meta:
        model = phone
        fields = ['photo']

#Расширение стандарной модели админки
class ProfileForm(forms.ModelForm):
    first_name1 = forms.CharField(widget=forms.TextInput(attrs={'class' : 'menuextras'}))

    class Meta:
        model = Profile
        fields = ['avatar', 'first_name1', 'last_name1']

sites/views.py
from aiogram.utils.mixins import DataMixin
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.apps import apps
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import redirect
from .forms import *
from  .models import *
from django.db.models import Q
from django.contrib.auth.decorators import login_required


import paramiko

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
passwd = "Jac" #Пароль для скриптов!!!


#from .forms import LoginForm

# Create your views here.
from django.urls import reverse_lazy
from sites.forms import LoginForm


def index(request):
    links = add_links.objects.all()
    return render(request, 'sites/index.html', {"links": links})

def phones(request):
    links_phone = phone.objects.all()
    result =''
    # Форма поиска
    form = SearchForm(request.GET or None)
    search = []
    if form.is_valid():
        search_query = form.cleaned_data['search_query']
        search = phone.objects.filter(Q(title__icontains=search_query)|Q(phone__icontains=search_query)|Q(job__icontains=search_query)|Q(mail__icontains=search_query))
    #Сохранение фото
    form1 = PhotoImg(request.POST, request.FILES)
    if request.method == 'POST':
        if form1.is_valid():
            form1.save()
            return redirect('product_list')
        else:
            form1 = ProductForm()
    return render(request, 'sites/phone.html', {"links_phone": links_phone, 'form':form,'form1':form1, 'search':search})

# def menu(request):
#     links_menu = menu_bd.objects.all()
#     return render(request, 'sites/menu.html',{"links_menu": links_menu})

def menu(request):
    links = add_links.objects.all()
    return render(request, 'sites/menu.html',{"links": links})

def add_phone(request):
    error = ''
    if request.method == 'POST':
        form = addPhone(request.POST)
        if form.is_valid():
            form.save()
        else:
            error = 'Форма не верная'
    form = addPhone()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'sites/add_phone.html', data)

def addlink(request):
    error = ''
    if request.method =='POST':
        form = addlinkForm(request.POST)
        if form.is_valid():
            form.save()
            print(form.cleaned_data)
        else:
            error = 'Форма не верная'
    form = addlinkForm()
    data = {
        'form':form,
        'error': error,
    }
    return render(request, 'sites/addlink.html', data)




#def login(request):
 #   return render(request, 'sites/login.html')

def base(request):
    links_menu = menu_bd.objects.all()
    return render(request, 'sites/base.html',{"links_menu": links_menu})

def menus(request):
    return render(request, 'sites/menus.html')

def def_test(request):
    sum = ''
    if request.method == 'POST':
        my_field_value = int(request.POST.get('my_field'))
        sum = 4 + my_field_value
        print(sum)
        if  my_field_value == 5:
            return redirect('index')
    else:
        my_field_value = None
    return render(request, 'sites/def_test.html', {'my_field': my_field_value, 'sum' : sum })

def rules(request):
    return render(request, 'sites/rules.html')

def info(request):
    return render(request, 'sites/info.html')

# def phone(request):
#     return render(request, 'sites/phone.html')


def open_1c (request): #Открыть правило для 1С SQL снаружи
    try:
        client.connect(hostname='10.100.2.1', port=6666, username="bka", password=passwd, look_for_keys=False,
                       allow_agent=False)
        _stdin, _stdout, _stderr = client.exec_command('ip firewall nat enable numbers=5')
        return render(request, 'sites/return.html')
        #return HttpResponse("Выполнено")
    except Exception:
        return render(request, 'sites/error.html')

def close_1c (request): #Закрыть правило для 1С SQL снаружи
    try:
        client.connect(hostname='10.100.2.1', port=6666, username="bka", password=passwd, look_for_keys=False,
                       allow_agent=False)
        _stdin, _stdout, _stderr = client.exec_command('ip firewall nat disable numbers=5')
        return render(request, 'sites/return.html')
        #return HttpResponse("Выполнено")
    except Exception:
        return render(request, 'sites/error.html')

def open_mik (request): #Закрыть правило для mikrotik снаружи
    try:
        client.connect(hostname='10.100.2.1', port=6666, username="bka", password=passwd, look_for_keys=False,
                       allow_agent=False)
        _stdin, _stdout, _stderr = client.exec_command('ip firewall nat enable numbers=2')
        return render(request, 'sites/return.html')
        #return HttpResponse("Выполнено")
    except Exception:
        return render(request, 'sites/error.html')


def close_mik (request): #Закрыть правило для mikrotik снаружи
    try:
        client.connect(hostname='10.100.2.1', port=6666, username="bka", password=passwd, look_for_keys=False,
                       allow_agent=False)
        _stdin, _stdout, _stderr = client.exec_command('ip firewall nat disable numbers=2')
        return render(request, 'sites/return.html')
        #return HttpResponse("Выполнено")
    except Exception:
        return render(request, 'sites/error.html')

def mik_res (request): #Перезагрузка MIkrotik
    try:
        client.connect(hostname='10.100.2.1', port=6666, username="bka", password=passwd, look_for_keys=False,
                       allow_agent=False)
        _stdin, _stdout, _stderr = client.exec_command('system reboot')
        return render(request, 'sites/return.html')
        #return HttpResponse("Выполнено")
    except Exception:
        return render(request, 'sites/error.html')

# def login_view(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password']
#             user = authenticate(request, username=username, password=password)
#             if user is not None:
#                 login(request, user)
#                 return redirect('home')
#     else:
#         form = LoginForm()
#     return render(request, 'sites/login.html', {'sites:form': form})

# class LoginUser(DataMixin, LoginView):
#     form_class = AuthenticationForm
#     template_name = 'sites/login.html'

    #
    # def get_context_data(self, *, object_list=None, **kwargs):
    #      context = super().get_context_data(**kwargs)
    #      c_def = self.get_user_context(title="Авторизация")
    #      return dict(list(context.items()) + list(c_def.items()))
class CustomLoginView(LoginView):
    authentication_form = AuthenticationForm
    template_name = 'sites/login.html'

    def get_success_url(self):
        return reverse_lazy('sites:index')

def logout_exit(request):
    logout(request)
    return redirect('index')

@login_required
def profile(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=profile)

        if form.is_valid():
            form.save()
    else:
        form = ProfileForm(instance=profile)

    return render(request,'sites/profile.html', {'user': user, 'profile': profile,'form': form},)

sites/templates/sites/bkp/index.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>mPurpose - Multipurpose Feature Rich Bootstrap Template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/icomoon-social.css' %}">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="{% static 'css/leaflet.css' %}" />
		<!--[if lte IE 8]>
		    <link rel="stylesheet" href="{% static 'css/leaflet.ie.css' %}" />
		<![endif]-->
		<link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->


        <!-- Navigation & Logo-->
        <div class="mainmenu-wrapper">
	        <div class="container">
	        	<div class="menuextras">
					<div class="extras">
						<ul>
			        		<li><a href="{% url 'sites:login' %}"><h4>Войти</h4></a></li>
							<li><a href=""><h4>Выйти</h4></a></li>
			        	</ul>
					</div>
		        </div>
		        <nav id="mainmenu" class="mainmenu">
					<ul>
						<li class="logo-wrapper"><a href="index.html"><img src="{% static 'img/mPurpose-logo.png' %}" alt="Multipurpose Twitter Bootstrap Template"></a></li>
						<li class="active">
							<a href="{% url 'index' %}">Главная</a>
						</li>
						<li>
							<a href="{% url 'sites:base' %}">BASE(for test)</a>
						</li>
						<li class="has-submenu">
							<a href="#">Pages +</a>
							<div class="mainmenu-submenu">
								<div class="mainmenu-submenu-inner">
									<div>
										<h4>Homepage</h4>
										<ul>
											<li><a href="index.html">Homepage (Sample 1)</a></li>
											<li><a href="page-homepage-sample.html">Homepage (Sample 2)</a></li>
										</ul>
										<h4>Services & Pricing</h4>
										<ul>
											<li><a href="page-services-1-column.html">Services/Features (Rows)</a></li>
											<li><a href="page-services-3-columns.html">Services/Features (3 Columns)</a></li>
											<li><a href="page-services-4-columns.html">Services/Features (4 Columns)</a></li>
											<li><a href="page-pricing.html">Pricing Table</a></li>
										</ul>
										<h4>Team & Open Vacancies</h4>
										<ul>
											<li><a href="page-team.html">Our Team</a></li>
											<li><a href="page-vacancies.html">Open Vacancies (List)</a></li>
											<li><a href="page-job-details.html">Open Vacancies (Job Details)</a></li>
										</ul>
									</div>
									<div>
										<h4>Our Work (Portfolio)</h4>
										<ul>
											<li><a href="page-portfolio-2-columns-1.html">Portfolio (2 Columns, Option 1)</a></li>
											<li><a href="page-portfolio-2-columns-2.html">Portfolio (2 Columns, Option 2)</a></li>
											<li><a href="page-portfolio-3-columns-1.html">Portfolio (3 Columns, Option 1)</a></li>
											<li><a href="page-portfolio-3-columns-2.html">Portfolio (3 Columns, Option 2)</a></li>
											<li><a href="page-portfolio-item.html">Portfolio Item (Project) Description</a></li>
										</ul>
										<h4>General Pages</h4>
										<ul>
											<li><a href="page-about-us.html">About Us</a></li>
											<li><a href="page-contact-us.html">Contact Us</a></li>
											<li><a href="page-faq.html">Frequently Asked Questions</a></li>
											<li><a href="page-testimonials-clients.html">Testimonials & Clients</a></li>
											<li><a href="page-events.html">Events</a></li>
											<li><a href="page-404.html">404 Page</a></li>
											<li><a href="page-sitemap.html">Sitemap</a></li>
											<li><a href="page-login.html">Login</a></li>
											<li><a href="page-register.html">Register</a></li>
											<li><a href="page-password-reset.html">Password Reset</a></li>
											<li><a href="page-terms-privacy.html">Terms & Privacy</a></li>
											<li><a href="page-coming-soon.html">Coming Soon</a></li>
										</ul>
									</div>
									<div>
										<h4>eShop</h4>
										<ul>
											<li><a href="page-products-3-columns.html">Products listing (3 Columns)</a></li>
											<li><a href="page-products-4-columns.html">Products listing (4 Columns)</a></li>
											<li><a href="page-products-slider.html">Products Slider</a></li>
											<li><a href="page-product-details.html">Product Details</a></li>
											<li><a href="page-shopping-cart.html">Shopping Cart</a></li>
										</ul>
										<h4>Blog</h4>
										<ul>
											<li><a href="page-blog-posts.html">Blog Posts (List)</a></li>
											<li><a href="page-blog-post-right-sidebar.html">Blog Single Post (Right Sidebar)</a></li>
											<li><a href="page-blog-post-left-sidebar.html">Blog Single Post (Left Sidebar)</a></li>
											<li><a href="page-news.html">Latest & Featured News</a></li>
										</ul>
									</div>
								</div><!-- /mainmenu-submenu-inner -->
							</div><!-- /mainmenu-submenu -->
						</li>
						<li>
							<a href="credits.html">Credits</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>

        <!-- Homepage Slider -->

				<div class="sequence-pagination-wrapper">
					<ul class="sequence-pagination">
						<li>1</li>
						<li>2</li>
						<li>3</li>
					</ul>
				</div>
			</div>
        </div>
        <!-- End Homepage Slider -->

		<!-- Press Coverage -->
        <div class="section">
	    	<div class="container">
				<div class="row">
					<div class="col-md-4 col-sm-6">
						<div class="service-wrapper">
							<a href="#" class="btn">Кнопочка</a><br> <br>
							<a href="#" class="btn">Кнопочка2</a><br> <br>
							<a href="#" class="btn">Кнопочка3</a>
						</div>
					</div>
					<div class="col-md-4 col-sm-6">
						<div class="service-wrapper">
							<a href="#" class="btn">Кнопочка</a><br> <br>
							<a href="#" class="btn">Кнопочка2</a><br> <br>
							<a href="#" class="btn">Кнопочка3</a>
						</div>
					</div>
					<div class="col-md-4 col-sm-6">
						<div class="service-wrapper">
							<a href="#" class="btn">Кнопочка</a><br> <br>
							<a href="#" class="btn">Кнопочка2</a><br> <br>
							<a href="#" class="btn">Кнопочка3</a>
						</div>
					</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Press Coverage -->

		<!-- Services -->
        <div class="section">
	        <div class="container">
	        	<div class="row">

	        	</div>
	        </div>
	    </div>
	    <!-- End Services -->

    </body>
</html>

sites/templates/sites/bkp/login.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>mPurpose - Multipurpose Feature Rich Bootstrap Template</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/icomoon-social.css' %}">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,800' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="{% static 'css/leaflet.css' %}" />
		<!--[if lte IE 8]>
		    <link rel="stylesheet" href="{% static 'css/leaflet.ie.css' %}" />
		<![endif]-->
		<link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->


        <!-- Navigation & Logo-->
        <div class="mainmenu-wrapper">
	        <div class="container">
	        	<div class="menuextras">
					<div class="extras">
						<ul>
			        		<li><a href="page-login.html">Вход</a></li>
			        	</ul>
					</div>
		        </div>
		        <nav id="mainmenu" class="mainmenu">
					<ul>
						<li class="logo-wrapper"><a href="index.html"><img src="{% static 'img/mPurpose-logo.png' %}" alt="Multipurpose Twitter Bootstrap Template"></a></li>
						<li>
							<a href="{% url 'index' %}">Главная</a>
						</li>
						<li>
							<a href="features.html">Features</a>
						</li>
						<li class="has-submenu active">
							<a href="#">Pages +</a>
							<div class="mainmenu-submenu">
								<div class="mainmenu-submenu-inner">
									<div>
										<h4>Homepage</h4>
										<ul>
											<li><a href="index.html">Homepage (Sample 1)</a></li>
											<li><a href="page-homepage-sample.html">Homepage (Sample 2)</a></li>
										</ul>
										<h4>Services & Pricing</h4>
										<ul>
											<li><a href="page-services-1-column.html">Services/Features (Rows)</a></li>
											<li><a href="page-services-3-columns.html">Services/Features (3 Columns)</a></li>
											<li><a href="page-services-4-columns.html">Services/Features (4 Columns)</a></li>
											<li><a href="page-pricing.html">Pricing Table</a></li>
										</ul>
										<h4>Team & Open Vacancies</h4>
										<ul>
											<li><a href="page-team.html">Our Team</a></li>
											<li><a href="page-vacancies.html">Open Vacancies (List)</a></li>
											<li><a href="page-job-details.html">Open Vacancies (Job Details)</a></li>
										</ul>
									</div>
									<div>
										<h4>Our Work (Portfolio)</h4>
										<ul>
											<li><a href="page-portfolio-2-columns-1.html">Portfolio (2 Columns, Option 1)</a></li>
											<li><a href="page-portfolio-2-columns-2.html">Portfolio (2 Columns, Option 2)</a></li>
											<li><a href="page-portfolio-3-columns-1.html">Portfolio (3 Columns, Option 1)</a></li>
											<li><a href="page-portfolio-3-columns-2.html">Portfolio (3 Columns, Option 2)</a></li>
											<li><a href="page-portfolio-item.html">Portfolio Item (Project) Description</a></li>
										</ul>
										<h4>General Pages</h4>
										<ul>
											<li><a href="page-about-us.html">About Us</a></li>
											<li><a href="page-contact-us.html">Contact Us</a></li>
											<li><a href="page-faq.html">Frequently Asked Questions</a></li>
											<li><a href="page-testimonials-clients.html">Testimonials & Clients</a></li>
											<li><a href="page-events.html">Events</a></li>
											<li><a href="page-404.html">404 Page</a></li>
											<li><a href="page-sitemap.html">Sitemap</a></li>
											<li><a href="page-login.html">Login</a></li>
											<li><a href="page-register.html">Register</a></li>
											<li><a href="page-password-reset.html">Password Reset</a></li>
											<li><a href="page-terms-privacy.html">Terms & Privacy</a></li>
											<li><a href="page-coming-soon.html">Coming Soon</a></li>
										</ul>
									</div>
									<div>
										<h4>eShop</h4>
										<ul>
											<li><a href="page-products-3-columns.html">Products listing (3 Columns)</a></li>
											<li><a href="page-products-4-columns.html">Products listing (4 Columns)</a></li>
											<li><a href="page-products-slider.html">Products Slider</a></li>
											<li><a href="page-product-details.html">Product Details</a></li>
											<li><a href="page-shopping-cart.html">Shopping Cart</a></li>
										</ul>
										<h4>Blog</h4>
										<ul>
											<li><a href="page-blog-posts.html">Blog Posts (List)</a></li>
											<li><a href="page-blog-post-right-sidebar.html">Blog Single Post (Right Sidebar)</a></li>
											<li><a href="page-blog-post-left-sidebar.html">Blog Single Post (Left Sidebar)</a></li>
											<li><a href="page-news.html">Latest & Featured News</a></li>
										</ul>
									</div>
								</div><!-- /mainmenu-submenu-inner -->
							</div><!-- /mainmenu-submenu -->
						</li>
						<li>
							<a href="credits.html">Credits</a>
						</li>
					</ul>
				</nav>
			</div>
		</div>

        <!-- Page Title -->
		<div class="section section-breadcrumbs">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<h1>Вход</h1>
					</div>
				</div>
			</div>
		</div>

        <div class="section">
	    	<div class="container">
				<div class="row">
					<div class="col-sm-5">
						<div class="basic-login">
							<form role="form" role="form">
								<div class="form-group">
		        				 	<label for="login-username"><i class="icon-user"></i> <b>Username or Email</b></label>
									<input class="form-control" id="login-username" type="text" placeholder="">
								</div>
								<div class="form-group">
		        				 	<label for="login-password"><i class="icon-lock"></i> <b>Password</b></label>
									<input class="form-control" id="login-password" type="password" placeholder="">
								</div>
								<div class="form-group">
									<label class="checkbox">
										<input type="checkbox"> Remember me
									</label>
									<a href="page-password-reset.html" class="forgot-password">Forgot password?</a>
									<button type="submit" class="btn pull-right">Login</button>
									<div class="clearfix"></div>
								</div>
							</form>
							<h2>Login</h2>
								<form method="post">
  									{% csrf_token %}
  									{{ form.as_p }}
  									<button type="submit">Login</button>
								</form>
						</div>
					</div>
				</div>
			</div>
		</div>
    </body>
</html>